# Starter pipeline


trigger:
- none

variables:
  serverName: 'azpipedbdemosvr.database.windows.net'
  varazuresubscription : 'PCSDSM(6270c2d6-d30a-41ec-8edb-519b950de71b)'
  databaseName: 'azpipedbdmo'
  SqlUsername: 'pcsadmin'
  SqlPassword: 'fX^%a^074Qua'
  SqlFile: 'PCS_Workshop.sql'

pool:
  vmImage: windows-latest

steps:

  - task: SqlAzureDacpacDeployment@1
    inputs:
      azureSubscription: 'PCSDSM (6270c2d6-d30a-41ec-8edb-519b950de71b)'
      AuthenticationType: 'server'
      ServerName: $(serverName)
      DatabaseName: $(databaseName)
      SqlUsername: $(SqlUsername)
      SqlPassword: $(SqlPassword)
      deployType: 'SqlTask'
      SqlFile: $(SqlFile)
      IpDetectionMethod: 'AutoDetect'